services:
  - type: web
    name: snake-backend
    env: docker
    dockerContext: backend
    dockerfilePath: backend/Dockerfile
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: snake-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: 60

  - type: web
    name: snake-frontend
    env: docker
    dockerContext: frontend
    dockerfilePath: frontend/Dockerfile
    plan: free
    envVars:
      - key: BACKEND_HOST
        value: snake-backend-a3io.onrender.com
      - key: BACKEND_PROTOCOL
        value: https
      - key: BACKEND_PORT
        value: 443

databases:
  - name: snake-db
    plan: free
    databaseName: snake_game
    user: snake_user
