name: CI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  docker-compose-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Set up Docker Compose
      uses: docker/setup-compose-action
      with:
        version: 'latest'


    - name: Create .env file
      run: cp .env.example .env

    - name: Verify Docker Compose Config
      run: docker-compose config

    - name: Build and Start Containers
      run: docker-compose up -d --build

    - name: Check Container Status
      run: docker-compose ps

    - name: Check Backend Logs (if failure)
      if: failure()
      run: docker-compose logs backend
